### ISSUE TITLE
Default Caching Directory

### ISSUE THREAD

**Issue by ztnel** [ztnel/myosin#57]
Assume a default caching directory rather than failing on model cache if  `MYOSIN_CACHE_BASE_PATH` is not defined. The code should assume a linux host operating system and create a new directory `myosin` directory under `/etc`. The definition for the default caching base path should be in one place and referenced across the codebase where required.

## Tasks
 - [ ] Log warning on init that `MYOSIN_CACHE_BASE_PATH` is unset and will use the default caching directory: `/etc/myosin`
 - [ ] If `MYOSIN_CACHE_BASE_PATH` is unset ensure `/etc/myosin` exists and set it as the global caching directory for all models
 - [ ] If `/etc/myosin` does not exist create a new directory.
